version: "3.11"

services:
  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
      - "443:443"

  django:
    build: .
    image: my-app:0.1
    command: gunicorn --bind 0.0.0.0:8000 django_app.wsgi:application --log-level INFO --workers=2 --threads=4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: <PASSWORD>
      POSTGRES_DB: django_app

  database:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: <PASSWORD>
      POSTGRES_DB: django_app
    volumes:
      - "./pg_data:/var/lib/postgresql/data"
