version: "3.11"

services:
  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    networks:
      - web

  django:
    build: .
    image: my-app:0.1
    command: gunicorn --bind 0.0.0.0:8000 django_app.wsgi:application --log-level INFO --workers=2 --threads=4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: <PASSWORD>
      POSTGRES_DB: django_app
    depends_on:
      - database
    networks:
      - backend
      - web

  database:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: <PASSWORD>
      POSTGRES_DB: django_app
    volumes:
      - "./pg_data:/var/lib/postgresql/data"
    networks:
      - backend

networks:
  web:
    ipam:
      config:
        subnet: 10.0.1.0/24
  backend:
    ipam:
      config:
        subnet: 10.0.2.0/24
